#@ load("@ytt:data","data")

# Requires: ENVIRONMENT, COMPONENT_NAME, STACK_NAME, RELEASE_VERSION

stages:
- plan
- deploy
- tag

plan:
  image: alpine:3.17.3
  stage: plan
  before_script:
    - apk add make
  script: 
    - make terraform-plan
  variables:
    ENVIRONMENT: #@ data.values.ENVIRONMENT
    STACK_NAME: #@ data.values.STACK_NAME

deploy:
  image: alpine:3.17.3
  stage: deploy
  before_script:
    - apk add make
  script: 
    - make terraform-apply
  variables:
    ENVIRONMENT: #@ data.values.ENVIRONMENT
    STACK_NAME: #@ data.values.STACK_NAME
  environment:
    name: #@ data.values.ENVIRONMENT + '-' + data.values.STACK_NAME
  release:
    tag_name: #@ data.values.ENVIRONMENT + '-' + data.values.STACK_NAME + '-' + data.values.RELEASE_VERSION
    description: 'Release'

tag:
  image: alpine:3.17.3
  stage: tag
  before_script:
    - apk add make
  script: 
    - make tag
  variables:
    ENVIRONMENT: #@ data.values.ENVIRONMENT
  release:
    tag_name: #@ data.values.ENVIRONMENT + '-' + data.values.COMPONENT_NAME + '-' + data.values.RELEASE_VERSION
    description: 'Component Release'
