stages:
- build
- test

variables:
  STACK_NAME: infra_canary
  PIPEGEN_TASK: check-terraform
  CHECK_TERRAFORM_STACK_NAME: $STACK_NAME

generate-pipeline:
  image: alpine:3.17.3
  stage: build
  before_script:
    - apk add make
  script: 
    - make pipegen-get-ytt
    - make pipegen-build
  artifacts:
    paths:
      - tmp/pipegen/$PIPEGEN_TASK/.gitlab-ci.yml

dynamic-test:
  stage: test
  trigger:
    include:
      - artifact: tmp/pipegen/$PIPEGEN_TASK/.gitlab-ci.yml
        job: generate-pipeline
