stages:
- plan
- deploy
- tag

variables:
  ENVIRONMENT: dev
  PRODUCT_NAME: labs
  SUBSYSTEM_NAME: canary
  STACK_NAME: infra-one
  STACK_VARIANT: default
  RELEASE_VERSION: 0.0.0

plan_terraform:
  image: alpine:3.17.3
  stage: plan
  before_script:
    - apk add make
  script:
    - make terraform-install
    - make terraform-init
    - make terraform-plan
  artifacts:
    when: on_success
    name: $PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/

deploy_terraform:
  image: alpine:3.17.3
  stage: deploy
  before_script:
    - apk add make
  script:
    - make terraform-install
    - make terraform-init
    - make terraform-apply
  dependencies:
    - plan_terraform
  environment:
    name: $ENVIRONMENT-$STACK_NAME

tag:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: tag
  script:
    - echo "Tag release of subsystem"
  release:
    tag_name: $ENVIRONMENT-$SUBSYSTEM_NAME-$RELEASE_VERSION
    description: 'Subsystem Release'
