
include:

  - local: '.gitlab/shared/core/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/rules/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/actions/terraform/.gitlab-ci.yml'

  ################################################################################

  # Components #

  # ctr-storage (default variant)
  - local: '.gitlab/pipelines/components/infra-canary-one/.gitlab-ci.yml'
  - local: '.gitlab/pipelines/components/infra-canary-two/.gitlab-ci.yml'
