variables:
  PROJECT_NAME: labs
  CI_DEFAULT_IMAGE: alpine:3.18.0
  CI_TF_IMAGE: $CI_DEFAULT_IMAGE

include:

  - local: '.gitlab/shared/core/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/rules/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/actions/terraform/.gitlab-ci.yml'

  ################################################################################

  # Components #

  # ctr-storage (default variant)
  - local: '.gitlab/pipelines/components/**/.gitlab-ci.yml'
