variables:
  PROJECT_NAME: labs
  CI_DEFAULT_IMAGE: alpine:3.18.3
  CI_PRE_COMMIT_IMAGE: python:3.10.12-slim-bullseye
  CI_TF_IMAGE: $CI_DEFAULT_IMAGE
  RELEASE_VERSION: $CI_COMMIT_SHORT_SHA

include:

  # Shared inclusions #

  - local: '.gitlab/shared/core/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/rules/standard/.gitlab-ci.yml'
  - local: '.gitlab/shared/actions/**/.gitlab-ci.yml'

  ################################################################################

  # Project #

  - local: '.gitlab/pipelines/project/**/.gitlab-ci.yml'

  # Components #

  - local: '.gitlab/pipelines/components/10-infra-enablement-default/.gitlab-ci.yml'
  - local: '.gitlab/pipelines/components/20-infra-compute-default/.gitlab-ci.yml'
