# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for GitLab pipelines
#
# See: https://docs.gitlab.com/ee/ci/pipelines/

stages:
  - validate
  - plan

variables:
  MISE_ENV: ci
  MISE_PARANOID: 1
  STACK: compute-coracle
  VARIANT: default

default:
  image: alpine:3.20.0

before_script:
  - apk update
  - apk upgrade --no-cache --no-interactive
  - apk add --no-cache --no-interactive bash curl git gnupg mise
  - mise trust --quiet .mise.toml
  - mise trust --quiet .mise.ci.toml
  - mise install --quiet task

validate:
  stage: validate
  script:
    - mise install --quiet terraform
    - mise exec task --command "task stack:init"
    - mise exec task --command "task stack:validate"
  variables:
    ENV: validate

plan_dev:
  stage: plan
  script:
    - mise install --quiet terraform
    - mise exec task --command "task stack:init"
    - mise exec task --command "task stack:plan"
  variables:
    ENV: dev

plan_test:
  stage: plan
  script:
    - mise install --quiet terraform
    - mise exec task --command "task stack:init"
    - mise exec task --command "task stack:plan"
  variables:
    ENV: test

plan_staging:
  stage: plan
  script:
    - mise install --quiet terraform
    - mise exec task --command "task stack:init"
    - mise exec task --command "task stack:plan"
  variables:
    ENV: staging

plan_prod:
  stage: plan
  script:
    - mise install --quiet terraform
    - mise exec task --command "task stack:init"
    - mise exec task --command "task stack:plan"
  variables:
    ENV: prod
