# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for GitLab pipelines
#
# See: https://docs.gitlab.com/ee/ci/pipelines/

stages:
  - pre_commit

variables:
  PRODUCT_NAME: labs
  STACK: compute-coracle
  VARIANT: default
  CI_PYTHON_IMAGE: python:3.12.4-bookworm
  TRIVY_NO_PROGRESS: "true"
  TRIVY_CACHE_DIR: ".trivycache/"

default:
  image: alpine:3.20.1

pre_commit:
  stage: pre_commit
  image: $CI_PYTHON_IMAGE
  script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install pre-commit
    - pre-commit run
  variables:
    ENV: pre_commit
  cache:
    paths:
      - .trivycache/
