# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for GitLab pipelines:
#
# See: https://docs.gitlab.com/ee/ci/pipelines/

stages:
  - validate
#  - plan
#  - apply-review
#  - apply-release

variables:
  ENV: test
  MISE_ENV: ci
  STACK: compute-coracle

default:
  image: alpine:3.20.0

before_script:
  - apk update
  - apk upgrade --no-cache --no-interactive
  - apk add --no-cache --no-interactive bash curl git gnupg mise
  - mise install task
  - mise install terraform

validate:
  stage: validate
  script:
    - task stack:init
    - task stack:validate
