# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for GitLab Pipelines
#
# See: https://docs.gitlab.com/ee/ci/pipelines/

stages:
  - secret_detection
  - pre_commit
  - tf_check
  - tf_plan
  - tf_update_review

variables:
  CI_PYTHON_IMAGE: python:3.12.4-slim-bookworm
  CI_TF_IMAGE: hashicorp/terraform:1.8.5

default:
  image: alpine:3.20.2

include:
  - component: gitlab.com/components/secret-detection/secret-detection@1.1.2
    inputs:
      stage: secret_detection

analyze_pre_commit:
  stage: pre_commit
  image: $CI_PYTHON_IMAGE
  extends:
    - .pre_commit_check
