stages:
- review

# variables:
#   ENVIRONMENT: dev
#   PRODUCT_NAME: labs
#   SUBSYSTEM_NAME: canary
#   STACK_NAME: infra-one
#   STACK_VARIANT: default
#   RELEASE_VERSION: 0.2.0

review_container_registry:
  stage: review
  variables:
    PRODUCT_NAME: labs
    SUBSYSTEM_NAME: ctr-storage
    STACK_VARIANT: $CI_COMMIT_REF_SLUG
  trigger:
    include: .gitlab/ci/workflows/subsystems/$SUBSYSTEM_NAME/review/.gitlab-ci.yml
  only:
    - branches
  except:
    - main

review_file_storage:
  stage: review
  variables:
    PRODUCT_NAME: labs
    SUBSYSTEM_NAME: file-storage
    STACK_VARIANT: $CI_COMMIT_REF_SLUG
  trigger:
    include: .gitlab/ci/workflows/subsystems/$SUBSYSTEM_NAME/review/.gitlab-ci.yml
  only:
    - branches
  except:
    - main
