# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for GitLab Pipelines
#
# See: https://docs.gitlab.com/ee/ci/pipelines/

stages:
  - secret_detection
  - pre_commit
  - tf_validate
  - tf_plan
  - tf_update_review

variables:
  CI_PYTHON_IMAGE: python:3.12.4-slim-bookworm
  CI_TF_IMAGE: debian:bookworm-slim
  AWS_REGION: eu-west-2
  DEBIAN_FRONTEND: noninteractive
  PRODUCT_NAME: labs
  TF_HTTP_LOCK_METHOD: 'POST'
  TF_HTTP_UNLOCK_METHOD: 'DELETE'
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: $CI_JOB_TOKEN
  TF_HTTP_RETRY_WAIT_MIN: '5'
  TF_INPUT: '0'
  TF_IN_AUTOMATION: 'true'


default:
  image: alpine:3.20.2

include:
  - local: ".gitlab/ci/actions/**/.gitlab-ci.yml"
  - component: gitlab.com/components/secret-detection/secret-detection@1.1.2
    inputs:
      stage: secret_detection

analyze_pre_commit:
  stage: pre_commit
  image: $CI_PYTHON_IMAGE
  extends:
    - .pre_commit_check

stack_validate_core-config:
  stage: tf_validate
  image: $CI_TF_IMAGE
  extends:
    - .stack_base
    - .stack_validate
  variables:
    ENV: dev
    STACK: core-config
    VARIANT: default
