# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for GitLab Pipelines
#

include:
  - component: gitlab.com/components/secret-detection/secret-detection@1.1.2
    inputs:
      stage: build
