variables:
  PROJECT_NAME: labs
  CI_DEFAULT_IMAGE: alpine:3.18.0
  CI_TF_IMAGE: $CI_DEFAULT_IMAGE
  PROJECT_VERSION: 0.1.4

include:

  # Shared inclusions #

  - local: '.gitlab/shared/core/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/rules/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/actions/terraform/.gitlab-ci.yml'

  ################################################################################

  # Components #

  - local: '.gitlab/pipelines/components/**/.gitlab-ci.yml'
