stages:
- analyze
- merge-request

# variables:
#   ENVIRONMENT: dev
#   PRODUCT_NAME: labs
#   SUBSYSTEM_NAME: canary
#   STACK_NAME: infra-one
#   STACK_VARIANT: default
#   RELEASE_VERSION: 0.2.0

analyze_code:
  stage: analyze
  trigger:
    include: .gitlab/ci/workflows/project/analyze/terraform/.gitlab-ci.yml
    strategy: depend

review_container_registry:
  stage: merge-request
  variables:
    PRODUCT_NAME: labs
    SUBSYSTEM_NAME: ctr-storage
    STACK_VARIANT: $CI_COMMIT_SHORT_SHA
  trigger:
    include: .gitlab/ci/workflows/subsystems/$SUBSYSTEM_NAME/merge-request/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

review_file_storage:
  stage: merge-request
  variables:
    PRODUCT_NAME: labs
    SUBSYSTEM_NAME: file-storage
    STACK_VARIANT: $CI_COMMIT_SHORT_SHA
  trigger:
    include: .gitlab/ci/workflows/subsystems/$SUBSYSTEM_NAME/merge-request/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
