variables:
  PROJECT_NAME: labs
  CI_DEFAULT_IMAGE: alpine:3.18.2
  CI_TF_IMAGE: $CI_DEFAULT_IMAGE
  RELEASE_VERSION: $CI_COMMIT_SHORT_SHA

include:

  # Shared inclusions #

  - local: '.gitlab/shared/core/stages/.gitlab-ci.yml'
  - local: '.gitlab/shared/rules/standard/.gitlab-ci.yml'
  - local: '.gitlab/shared/actions/terraform/.gitlab-ci.yml'

  ################################################################################

  # Components #

  - local: '.gitlab/pipelines/components/**/.gitlab-ci.yml'
