stages:
- build
- test

generate-pipeline:
  image: alpine:3.17.3
  stage: build
  before_script:
    - apk add make
  script: 
    - make pipegen-get-ytt
    - make pipegen-build
  artifacts:
    paths:
      - tmp/pipegen/.gitlab-ci.yml # FIXME: Check path

dynamic-test:
  stage: test
  trigger:
    include:
      - artifact: tmp/pipegen/.gitlab-ci.yml
        job: generate-pipeline
