# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#

[tools]
awscli = "latest"
python = "3.12.3"
task = "3.37.2"
terraform = "1.8.2"
trivy = "latest"

[env]
PRODUCT_NAME = 'labs'
VARIANT = 'default'

# TF: Disable use of Hashicorp Checkpoint service
CHECKPOINT_DISABLE = 'true'

# GitLab: Specify ID of project
GITLAB_PROJECT_ID = '44821683'
