# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#

[tools]
awscli = "latest"
hugo = "0.122.0"
python = "3.12.3"
task = "3.36.0"
terraform = "1.8.2"
trivy = "latest"

[env]
_.file = ["{{env.HOME}}/.gitlab-creds", "{{env.ENV}}.env"]
