# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#

[env]
ENV = 'dev'

# AWS CLI
AWS_PROFILE = 'origin-human'

# TF: Use GitLab HTTP backend for TF state
_.file = ["{{env.HOME}}/.gitlab/creds"]
TF_HTTP_LOCK_METHOD = 'POST'
TF_HTTP_UNLOCK_METHOD = 'DELETE'
TF_HTTP_USERNAME = "{{env.GITLAB_USERNAME}}"
TF_HTTP_PASSWORD = "{{env.GITLAB_ACCESS_TOKEN}}"
TF_HTTP_RETRY_WAIT_MIN = '5'
