# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#

[tools]
awscli = "latest"
python = "3.12.3"
task = "3.37.2"
terraform = "1.8.2"
trivy = "latest"

[env]
PRODUCT_NAME = 'labs'
GITLAB_PROJECT_ID = '44821683'
VARIANT = 'default'
