# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for mise-en-place
#
# See: https://mise.jdx.dev

[tools]
awscli = "latest"
python = "3.12.3"
task = "3.37.2"
terraform = "1.8.2"
trivy = "latest"

[env]
# Project: Product name
PRODUCT_NAME = 'labs'

# TF: Disable use of Hashicorp Checkpoint service
CHECKPOINT_DISABLE = 'true'

# GitLab: Specify ID of project
GITLAB_PROJECT_ID = '44821683'
