# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#

[tools]
awscli = "latest"
hugo = "0.122.0"
python = "3.12.3"
task = "3.37.1"
terraform = "1.8.2"
trivy = "latest"

[env]
_.file = ["{{env.HOME}}/.gitlab/creds"]

PRODUCT_NAME = 'labs'

CHECKPOINT_DISABLE = 'true'

GITLAB_PROJECT_ID = '44821683'

TF_HTTP_LOCK_METHOD = 'POST'
TF_HTTP_UNLOCK_METHOD = 'DELETE'
TF_HTTP_USERNAME = "{{env.GITLAB_USERNAME}}"
TF_HTTP_PASSWORD = "{{env.GITLAB_ACCESS_TOKEN}}"
TF_HTTP_RETRY_WAIT_MIN = '5'

# Options to support non-interactive use
TF_INPUT = '0'
TF_IN_AUTOMATION = 'true'
