# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#

[env]
# TF: Use GitLab HTTP backend for TF state
TF_HTTP_LOCK_METHOD = 'POST'
TF_HTTP_UNLOCK_METHOD = 'DELETE'
TF_HTTP_USERNAME = "gitlab-ci-token"
TF_HTTP_PASSWORD = "{{env.CI_JOB_TOKEN}}"
TF_HTTP_RETRY_WAIT_MIN = '5'

# TF: Options to support non-interactive use
TF_INPUT = '0'
TF_IN_AUTOMATION = 'true'
