# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for REUSE:
#
# https://reuse.software/

version = 1
SPDX-PackageName = "stuartellis-org-infra-labs"
SPDX-PackageSupplier = "Stuart Ellis <https://www.stuartellis.name>"
SPDX-PackageDownloadLocation = "https://github.com/stuartellis/FIXME"

[[annotations]]
path = ".terraform-version"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".tool-versions"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "CC0-1.0"
