
## Component Definition

.comp_infra_canary_two:
  variables:
    COMPONENT_NAME: infra-canary-two
    PRODUCT_NAME: labs
    STACK_VARIANT: default
    RULES_CHANGES_PATH_1: "terraform1/stacks/definitions/$STACK_NAME/**/*"

    # FIXME
    # RULES_CHANGES_PATH_2: "terraform1/stacks/environments/**/$STACK_NAME.tfvars"
    RULES_CHANGES_PATH_2: ".gitlab/**/*"

## Stages

infra-canary_analyze_two:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-two
  stage: analyze
  needs: []
  extends:
   - .comp_infra_canary
   - .rules_analyze
   - .action_analyze_terraform

# infra-canary_mr_checks:
#   variables:
#     ENVIRONMENT: dev
#     STACK_NAME: infra-two
#   stage: mr_checks
#   extends:
#    - .comp_infra_canary
#    - .stage_mr_checks
#   needs: ["infra-canary_analyze"]

infra-canary_two_plan_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-two
    TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-plan.json
  stage: review
  needs: ["infra-canary_two_analyze"]
  extends:
    - .comp_infra_canary
    - .rules_plan
    - .action_plan_terraform

infra-canary_two_review_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-two
  stage: review
  needs: ["infra-canary_two_plan_dev"]
  dependencies:
    - infra-canary_plan_dev
  extends:
    - .comp_infra_canary_two
    - .rules_deploy_review
    - .action_deploy_tf_review

# infra-canary_two_release:
  # variables:
  #   ENVIRONMENT: dev
  #   STACK_NAME: infra-two
  #   TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-plan.json
#   stage: release
#   extends:
#    - .comp_infra_canary
#    - .stage_release
#   needs: ["infra-canary_analyze"]
