stages:
- deploy_review

review_container_registry:
  stage: deploy_review
  variables:
    PRODUCT_NAME: labs
    COMPONENT_NAME: ctr-storage
    STACK_VARIANT: $CI_COMMIT_SHORT_SHA
  trigger:
    include: .gitlab/ci/workflows/components/$COMPONENT_NAME/merge_request/.gitlab-ci.yml
    strategy: depend

review_file_storage:
  stage: deploy_review
  variables:
    PRODUCT_NAME: labs
    COMPONENT_NAME: file-storage
    STACK_VARIANT: $CI_COMMIT_SHORT_SHA
  trigger:
    include: .gitlab/ci/workflows/components/$COMPONENT_NAME/merge_request/.gitlab-ci.yml
    strategy: depend
