## Component Definition

.comp_bastion-service:
  variables:
    COMPONENT_NAME: bastion-service
    PRODUCT_NAME: labs
    STACK_VARIANT: default

## Stages

bastion-service_linting:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: compute-bastion
  stage: analyze-linting
  needs: ["project_pre-commit_default"]
  rules:
    - !reference [.rules_mr_trigger_tf, rules]
  extends:
    - .comp_bastion-service
    - .action_analyze_terraform

bastion-service_plan_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: compute-bastion
    TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-plan.json
  artifacts:
    when: always
    name: $PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/terraform
  stage: build-tf-plan
  needs: ["bastion-service_linting"]
  rules:
    - !reference [.rules_mr_trigger_tf, rules]
  extends:
    - .comp_bastion-service
    - .action_plan_terraform

bastion-service_review_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: compute-bastion
  stage: review
  needs: ["bastion-service_plan_dev"]
  rules:
    - !reference [.rules_mr_trigger_tf, rules]
  dependencies:
    - bastion-service_plan_dev
  extends:
    - .comp_bastion-service
    - .action_deploy_tf_review
  resource_group: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
  environment:
    name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
    deployment_tier: development
#    on_stop: bastion-service_stop_dev
#     # url: https://$CI_ENVIRONMENT_SLUG.action_example.action_com

# bastion-service_stop_dev:
#   variables:
#     ENVIRONMENT: dev
#     STACK_NAME: compute-bastion
#   stage: review
#   rules:
#     - !reference [.rules_mr_trigger_tf, rules]
#   extends:
#     - .comp_bastion-service
#     - .action_deploy_tf_review
#   environment:
#     name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
#     deployment_tier: development
#     action: stop
#   when: manual

# bastion-service_plan_test:
#   variables:
#     ENVIRONMENT: test
#     STACK_NAME: compute-bastion
#     TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-plan.json
#   artifacts:
#     when: always
#     name: $PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-tfplan
#     expire_in: 1 week
#     paths:
#       - tmp/terraform
#   stage: build-tf-plan
#   needs: ["bastion-service_linting"]
#   rules:
#     - !reference [.rules_main_trigger_tf, rules]
#   extends:
#     - .comp_bastion-service
#     - .action_plan_terraform

# bastion-service_release_test:
#   variables:
#     ENVIRONMENT: test
#     STACK_NAME: compute-bastion
#   stage: deploy-release
#   needs: ["bastion-service_plan_test"]
#   rules:
#     - !reference [.rules_main_trigger_tf, rules]
#   dependencies:
#     - bastion-service_plan_test
#   extends:
#     - .comp_bastion-service
#     - .action_deploy_tf_release
#   resource_group: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
#   environment:
#     name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
#     deployment_tier: testing
#     # url: https://$CI_ENVIRONMENT_SLUG.action_example.action_com

# bastion-service_tag_test:
#   variables:
#     ENVIRONMENT: test
#     STACK_NAME: compute-bastion
#   stage: tag-release
#   needs: ["bastion-service_release_test"]
#   rules:
#     - !reference [.rules_main_trigger_tf, rules]
#   extends:
#     - .comp_bastion-service
#     - .action_tag_release
