
plan_terraform:
  image: alpine:3.17.3
  stage: plan
  before_script:
    - apk add --no-cache jq make
  script:
    - make terraform-install
    - make terraform-init
    - make terraform-plan
  artifacts:
    when: on_success
    name: $PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/terraform
