stages:
- analyze_terraform

analyze_terraform:
  stage: analyze_terraform
  image: alpine:3.18.0
  before_script:
    - apk add --no-cache curl git jq make unzip
  script:
    - make terraform-dummy
  rules:
    - changes:
        - terraform1/*
