
## Component Definition

.comp_infra-canary-one:
  variables:
    COMPONENT_NAME: infra-canary-one
    PRODUCT_NAME: labs
    STACK_VARIANT: default

## Stages

infra-canary-one_analyze:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-one
  stage: analyze
  needs: []
  rules:
    - !reference [.rules_branch_tf_push, rules]
  extends:
   - .comp_infra-canary-one
   - .action_analyze_terraform

infra-canary-one_plan_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-one
    TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-plan.json
  artifacts:
    when: always
    name: $PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/terraform
  stage: plan
  needs: ["infra-canary-one_analyze"]
  rules:
    - !reference [.rules_branch_tf_push, rules]
  extends:
    - .comp_infra-canary-one
    - .action_plan_terraform

infra-canary-one_review_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-one
  stage: review
  needs: ["infra-canary-one_plan_dev"]
  rules:
    - !reference [.rules_branch_tf_push, rules]
  dependencies:
    - infra-canary-one_plan_dev
  extends:
    - .comp_infra-canary-one
    - .action_deploy_tf_review
  resource_group: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
  environment:
    name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
    deployment_tier: development
#    on_stop: infra-canary-one_stop_dev
#     # url: https://$CI_ENVIRONMENT_SLUG.action_example.action_com

# infra-canary-one_stop_dev:
#   variables:
#     ENVIRONMENT: dev
#     STACK_NAME: infra-one
#   stage: review
#   rules:
#     - !reference [.rules_branch_tf_push, rules]
#   extends:
#     - .comp_infra-canary-one
#     - .action_deploy_tf_review
#   environment:
#     name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
#     deployment_tier: development
#     action: stop
#   when: manual

infra-canary-one_plan_test:
  variables:
    ENVIRONMENT: test
    STACK_NAME: infra-one
    TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-plan.json
  artifacts:
    when: always
    name: $PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/terraform
  stage: plan
  needs: ["infra-canary-one_analyze"]
  rules:
    - !reference [.rules_branch_tf_push, rules]
  extends:
    - .comp_infra-canary-one
    - .action_plan_terraform

infra-canary-one_release_test:
  variables:
    ENVIRONMENT: test
    STACK_NAME: infra-one
  stage: release
  needs: ["infra-canary-one_plan_test"]
  rules:
    - !reference [.rules_branch_tf_push, rules]
  dependencies:
    - infra-canary-one_plan_test
  extends:
    - .comp_infra-canary-one
    - .action_deploy_tf_release
  resource_group: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
  environment:
    name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
    deployment_tier: testing
#     # url: https://$CI_ENVIRONMENT_SLUG.action_example.action_com

infra-canary-one_tag_test:
  variables:
    ENVIRONMENT: test
    STACK_NAME: infra-one
  stage: post_release
  needs: ["infra-canary-one_release_test"]
  rules:
    - !reference [.rules_branch_tf_push, rules]
  extends:
   - .comp_infra-canary-one
   - .action_tag_release
