
## Component Definition

.comp_infra-canary-one:
  variables:
    COMPONENT_NAME: infra-canary-one
    PRODUCT_NAME: labs
    STACK_VARIANT: default

## Stages

infra-canary-one_analyze:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-one
  stage: analyze
  needs: []
  rules:
    - !reference [.rules_tf_analyze, rules]
  extends:
   - .comp_infra-canary-one
   - .action_analyze_terraform

# infra-canary-one_mr_checks:
#   variables:
#     ENVIRONMENT: dev
#     STACK_NAME: infra-one
#   stage: mr_checks
#   extends:
#    - .comp_infra-canary-one
#    - .stage_mr_checks
#   needs: ["infra-canary_analyze"]

infra-canary-one_plan_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-one
    TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-plan.json
  artifacts:
    when: always
    name: $PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/terraform
  stage: plan
  needs: ["infra-canary-one_analyze"]
  rules:
    - !reference [.rules_tf_plan, rules]
  extends:
    - .comp_infra-canary-one
    - .action_plan_terraform

infra-canary-one_review_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-one
  stage: review
  needs: ["infra-canary-one_plan_dev"]
  rules:
    - !reference [.rules_tf_deploy_review, rules]
  dependencies:
    - infra-canary-one_plan_dev
  extends:
    - .comp_infra-canary-one
    - .action_deploy_tf_review
  environment:
    name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
    deployment_tier: development
    on_stop: infra-canary-one_stop_dev
#     # url: https://$CI_ENVIRONMENT_SLUG.action_example.action_com

infra-canary-one_stop_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: infra-one
  stage: review
  rules:
    - !reference [.rules_tf_stop_review, rules]
  extends:
    - .comp_infra-canary-one
    - .action_stop_tf_review
  environment:
    name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_VARIANT
    deployment_tier: development
    action: stop

# infra-canary-one_release:
#   variables:
#     ENVIRONMENT: dev
#     STACK_NAME: infra-one
#     TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-plan.json
#   stage: release
#   needs: ["infra-canary-one_review_dev"]
#   rules:
#     - !reference [.rules_tf_deploy_release, rules]
#   extends:
#    - .comp_infra-canary-one
#    - .rules_tf_deploy_release
