## Component Definition

.comp_infra-enablement:
  variables:
    COMPONENT_NAME: infra-enablement
    PRODUCT_NAME: labs
    STACK_VARIANT: default

## Stages

infra_compute_compute-site-checker_linting:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: compute-site-checker
  stage: analyze-linting
  needs: ["project_pre-commit_default"]
  rules:
    - !reference [.rules_mr_trigger_tf, rules]
  extends:
    - .comp_infra-enablement
    - .action_analyze_terraform

infra_compute_compute-site-checker_plan_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: compute-site-checker
    TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-plan.json
  artifacts:
    when: always
    name: $PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/build
      - tmp/terraform
  stage: build-tf-plan
  needs: ["infra_compute_compute-site-checker_linting"]
  rules:
    - !reference [.rules_mr_trigger_tf, rules]
  extends:
    - .comp_infra-enablement
    - .action_plan_terraform

infra_compute_compute-site-checker_review_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: compute-site-checker
  stage: review
  needs: ["infra_compute_compute-site-checker_plan_dev"]
  rules:
    - !reference [.rules_mr_trigger_tf, rules]
  dependencies:
    - infra_compute_compute-site-checker_plan_dev
  extends:
    - .comp_infra-enablement
    - .action_deploy_tf_review
  resource_group: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
  environment:
    name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
    deployment_tier: development
    on_stop: infra_compute_compute-site-checker_stop_dev
#     # url: https://$CI_ENVIRONMENT_SLUG.action_example.action_com

infra_compute_compute-site-checker_stop_dev:
  variables:
    ENVIRONMENT: dev
    STACK_NAME: compute-site-checker
  stage: review
  rules:
    - !reference [.rules_mr_trigger_tf, rules]
  extends:
    - .comp_infra-enablement
    - .action_stop_tf_review
  environment:
    name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
    deployment_tier: development
    action: stop
  when: manual

# infra_compute_compute-site-checker_plan_test:
#   variables:
#     ENVIRONMENT: test
#     STACK_NAME: compute-site-checker
#     TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-plan.json
#   artifacts:
#     when: always
#     name: $PRODUCT_NAME-$ENVIRONMENT-$STACK_NAME-$STACK_VARIANT-tfplan
#     expire_in: 1 week
#     paths:
#       - tmp/terraform
#   stage: build-tf-plan
#   needs: ["infra_compute_compute-site-checker_linting"]
#   rules:
#     - !reference [.rules_main_trigger_tf, rules]
#   extends:
#     - .comp_infra-enablement
#     - .action_plan_terraform

# infra_compute_compute-site-checker_release_test:
#   variables:
#     ENVIRONMENT: test
#     STACK_NAME: compute-site-checker
#   stage: deploy-release
#   needs: ["infra_compute_compute-site-checker_plan_test"]
#   rules:
#     - !reference [.rules_main_trigger_tf, rules]
#   dependencies:
#     - infra_compute_compute-site-checker_plan_test
#   extends:
#     - .comp_infra-enablement
#     - .action_deploy_tf_release
#   resource_group: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
#   environment:
#     name: $PRODUCT_NAME/$ENVIRONMENT/$STACK_NAME/$STACK_VARIANT
#     deployment_tier: testing
# #     # url: https://$CI_ENVIRONMENT_SLUG.action_example.action_com

# infra_compute_compute-site-checker_tag_test:
#   variables:
#     ENVIRONMENT: test
#     STACK_NAME: compute-site-checker
#   stage: tag-release
#   needs: ["infra_compute_compute-site-checker_release_test"]
#   rules:
#     - !reference [.rules_main_trigger_tf, rules]
#   extends:
#     - .comp_infra-enablement
#     - .action_tag_release
