stages:
- plan
- deploy

variables:
  ENVIRONMENT: dev
  STACK_NAME: infra-one
  TF_PLAN_JSON: tmp/terraform/$PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-plan.json

plan_terraform:
  stage: plan
  image: alpine:3.17.3
  before_script:
    - apk add --no-cache make
  script:
    - make terraform-install
    - make terraform-init
    - make terraform-plan
    - make terraform-show-json
  artifacts:
    when: on_success
    name: $PRODUCT_NAME-$STACK_NAME-$ENVIRONMENT-$STACK_VARIANT-tfplan
    expire_in: 1 week
    paths:
      - tmp/terraform
    reports:
      terraform: $TF_PLAN_JSON

deploy_review_app:
  stage: deploy
  image: alpine:3.17.3
  before_script:
    - apk add --no-cache make
  script:
    - make terraform-install
    - make terraform-init
    - make terraform-apply
  dependencies:
    - plan_terraform
  environment:
    name: dev/$STACK_VARIANT
    deployment_tier: development
    on_stop: stop_review
    # url: https://$CI_ENVIRONMENT_SLUG.example.com

stop_review:
  stage: deploy
  image: alpine:3.17.3
  before_script:
    - apk add --no-cache make
  script:
    - make terraform-install
    - make terraform-init
    - make terraform-destroy
  environment:
    name: dev/$STACK_VARIANT
    action: stop
  when: manual
