#cloud-config

output: {all: "| tee -a /var/log/cloud-init-output.log"}

users:
  - default
  - name: ${automation_username}
    gecos: ${automation_username}
    primary_group: ${automation_username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin

final_message: "[INFO] cloud-init process complete"
