# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for GitLab Pipelines
#
# See: https://docs.gitlab.com/ee/ci/pipelines/

.stack_base:
  before_script:
    - apk add go-task

.stack_apply:
  script:
    - go-task stack:apply

.stack_destroy:
  script:
    - go-task stack:destroy

.stack_plan:
  script:
    - go-task stack:plan

.stack_test:
  script:
    - go-task stack:test

.stack_validate:
  script:
    - go-task stack:check-fmt
    - go-task stack:validate
