# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for GitLab Pipelines
#
# See: https://docs.gitlab.com/ee/ci/pipelines/

.stack_base:
  before_script:
    - apt-get update -qy && apt-get install -qy curl git
    - apt-get install -qy --no-install-recommends apt-transport-https gnupg lsb-release
    - ./scripts/install-task.sh -b /usr/local/bin $(grep 'task' .tool-versions | cut -d ' ' -f 2)
    - task ci:install-terraform

.stack_apply:
  script:
    - task stack:apply

.stack_destroy:
  script:
    - task stack:destroy

.stack_plan:
  script:
    - task stack:init
    - task stack:plan

.stack_test:
  script:
    - task stack:init
    - task stack:test

.stack_validate:
  script:
    - task stack:init
    - task stack:check-fmt
    - task stack:validate
