# Example rules set
#
# .base_rules:
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#       when: always
#     - if: '$CI_PIPELINE_SOURCE == "push"'
#       when: never
#     - if: $CI_COMMIT_TAG
#       when: never
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       changes:
#         - $RULES_CHANGES_PATH_1
#         - $RULES_CHANGES_PATH_2
#     - when: manual
#       allow_failure: true

# - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   when: always
# - if: '$CI_PIPELINE_SOURCE == "push"'
#   when: never
# - if: $CI_COMMIT_TAG
#   when: never

.rules_default_trigger_anyfile:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# .rules_branch_trigger_anyfile:
#   rules:
#     - if: $CI_COMMIT_TAG
#       when: never
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       when: never
#     - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
#       when: never
#     - if: "$CI_PIPELINE_SOURCE != $CI_DEFAULT_BRANCH"
#       when: on_success

.rules_mr_trigger_lambda:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "python/lambdas/$APP_NAME/**/*"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - "python/lambdas/$APP_NAME/**/*"

.rules_main_trigger_lambda:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - "python/lambdas/$APP_NAME/**/*"

.rules_mr_trigger_tf:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "terraform1/stacks/definitions/$STACK_NAME/**/*"
        - "terraform1/stacks/environments/**/$STACK_NAME.tfvars"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - "terraform1/stacks/definitions/$STACK_NAME/**/*"
        - "terraform1/stacks/environments/**/$STACK_NAME.tfvars"

.rules_main_trigger_tf:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - "terraform1/stacks/definitions/$STACK_NAME/**/*"
        - "terraform1/stacks/environments/**/$STACK_NAME.tfvars"
