# Example rules set
#
# .base_rules:
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#       when: always
#     - if: '$CI_PIPELINE_SOURCE == "push"'
#       when: never
#     - if: $CI_COMMIT_TAG
#       when: never
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       changes:
#         - $RULES_CHANGES_PATH_1
#         - $RULES_CHANGES_PATH_2
#     - when: manual
#       allow_failure: true

# - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   when: always
# - if: '$CI_PIPELINE_SOURCE == "push"'
#   when: never
# - if: $CI_COMMIT_TAG
#   when: never

.rules_branch_tf_push:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "terraform1/stacks/definitions/$STACK_NAME/**/*"
        - "terraform1/stacks/environments/**/$STACK_NAME.tfvars"
